project:
  type: website

website:
  title: "Thorarinn Jonmundsson"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: zephyr
    css: styles.css
execute:
  freeze: auto



