project:
  type: website

website:
  title: "Thorarinn Jonmundsson"
  site-url: "https://tjonmundsson.com"
  description: "Thor's online notebook"
  navbar:
    right:
      - about.qmd
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.com/citations?hl=en&user=1ZqKlIkAAAAJ
      - icon: linkedin
        href: https://www.linkedin.com/in/thorarinnj/
      - icon: github
        href: https://github.com/
  cookie-consent: false
format:
  html:
    theme: 
      light: theme.scss
      dark: theme-dark.scss
execute:
  freeze: auto



