project:
  type: website

website:
  title: "Thorarinn Jonmundsson"
  site-url: "https://tjonmundsson.com"
  description: "Thor's online notebook"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  cookie-consent: false
format:
  html:
    theme: 
      light: theme.scss
      dark: theme-dark.scss
execute:
  freeze: auto



